repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.1.0"
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@3.2.5

  - repo: local
    hooks:
      - id: gofmt
        name: GO formatting
        language: system
        entry: >
          go fmt
        always_run: true
        fail_fast: true
        files: \.go$
