name: Build & Test

on:
  push:
    branches: ["main"]
  pull_request:

env:
  TERM: xterm
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          submodules: true

      - name: Set up Go
        uses: actions/setup-go@v5.5.0
        with:
          go-version: "1.22"

      - name: Set up bats
        uses: mig4/setup-bats@v1.2.0

      - name: Build & Test
        run: make

      - name: Print version
        run: ./bin/fa-lint -version
